### ISSUE TITLE
How are you going to handle dependencies?

### ISSUE THREAD

**Issue by WitherCubes** [gersonwahyudi/speedovoid#2]
Are you going to ask manually if a user has a dependencies file or automatically detect if a user has dependencies file?

- If you are manually asking the user, see this commit - https://github.com/WitherCubes/speedovoid/tree/asking-user
(or)
- If you are automatically detecting dependencies file, see this commit - https://github.com/WitherCubes/speedovoid/tree/automatic

**Comment by gersonwahyudi** [comment]
I already fixed the script to automatically read the user input dependencies file, thanks for the issue
